import type Logger from 'zigbee2mqtt/util/logger';

import { vi } from 'vitest';
import * as Settings from 'zigbee2mqtt/util/settings';
import Device from 'zigbee2mqtt/model/device';
import { XikibotExtension } from '../../src/xikibot';
import { nonPartial } from './test-util';
import { xikibotInstance } from '../../src/global';

const settingsMock: Partial<typeof Settings> = {
  get: () => Settings.defaults as any,
};

const loggerMock: Partial<typeof Logger> = {
  info: vi.fn().mockImplementation((messageOrLambda, namespace = 'z2m') => log('info', messageOrLambda, namespace)),
  warning: vi.fn().mockImplementation((messageOrLambda, namespace = 'z2m') => log('warning', messageOrLambda, namespace)),
  error: vi.fn().mockImplementation((messageOrLambda, namespace = 'z2m') => log('error', messageOrLambda, namespace)),
  debug: vi.fn().mockImplementation((messageOrLambda, namespace = 'z2m') => log('debug', messageOrLambda, namespace)),
};

function log(level: Settings.LogLevel, messageOrLambda: string | (() => string), namespace: string) {
  console.log(`[${level}] ${namespace}: ${messageOrLambda instanceof Function ? messageOrLambda() : messageOrLambda}`);
}

interface DeviceMockOptions {
  ieeeAddr?: string;
  disabled?: boolean;
};

class DeviceMock implements Partial<Device> {
  private static autoGeneratedIeeeAddr = 100;

  private readonly _name: string;
  private readonly _ieeeAddr: string;
  private _disabled: boolean | undefined;
  private state?: KeyValue;

  constructor(name: string, options?: DeviceMockOptions) {
    this._name = name;
    this._ieeeAddr = options?.ieeeAddr ?? (DeviceMock.autoGeneratedIeeeAddr++).toString(16).padStart(16, '0');
    this._disabled = options?.disabled;
  }

  /// Mocked functions ///

  get name() {
    return this._name;
  }

  get ieeeAddr() {
    return this._ieeeAddr;
  }

  get ID() {
    return this._ieeeAddr;
  }

  get options(): DeviceOptionsWithId {
    return {
      ID: this._ieeeAddr,
      friendly_name: this._name,
      disabled: this._disabled,
    };
  }

  /// Custom functions ///

  getState(): KeyValue | undefined {
    return this.state;
  }

  setState(state: KeyValue | undefined): void {
    this.state = state;
  }

  setDisabled(disabled: boolean) {
    this._disabled = disabled;
  }
}

export class XikibotExtensionMock extends XikibotExtension {
  private devices = new Map<string, DeviceMock>();
  private devicesCreateAuto = true;

  constructor() {
    super(
      undefined!, // zigbee
      undefined!, // mqtt
      undefined!, // state
      undefined!, // publishEntityState
      undefined!, // eventBus
      undefined!, // enableDisableExtension
      undefined!, // restartCallback
      undefined!, // addExtension
      nonPartial(settingsMock), // settings
      nonPartial(loggerMock), // logger
    );
  }

  /// Mocked functions ///

  emitMessage(payload: KeyValue, ...topicParts: string[]) {
    console.log(`Message emitted to topic "${topicParts.join('/')}":`, JSON.stringify(payload));
  }

  getState(name: string): KeyValue | null {
    return (this.getDevice(name) as DeviceMock | null)?.getState() ?? null;
  }

  getDevice(name: string): Device | null {
    let device = this.devices.get(name);
    if (!device && this.devicesCreateAuto) {
      device = this.addDevice(name);
    }
    return nonPartial(device) ?? null;
  }

  /// Custom functions ///

  static getDevice(name: string): DeviceMock | null {
    return (xikibotInstance as XikibotExtensionMock).getDevice(name) as DeviceMock | null;
  }

  static setDeviceState(name: string, state: KeyValue) {
    XikibotExtensionMock.getDevice(name)?.setState(state);
  }

  static setDevicesCreateAuto(enabled: boolean) {
    (xikibotInstance as XikibotExtensionMock).devicesCreateAuto = enabled;
  }

  static addDevice(name: string, options?: DeviceMockOptions): DeviceMock {
    return (xikibotInstance as XikibotExtensionMock).addDevice(name, options);
  }

  static removeDevice(name: string) {
    (xikibotInstance as XikibotExtensionMock).devices.delete(name);
  }

  static disableDevice(name: string) {
    XikibotExtensionMock.getDevice(name)?.setDisabled(true);
  }

  static enableDevice(name: string) {
    XikibotExtensionMock.getDevice(name)?.setDisabled(false);
  }

  private addDevice(name: string, options?: DeviceMockOptions): DeviceMock {
    const device = new DeviceMock(name, options);
    this.devices.set(name, device);
    return device;
  }
}
